docs_dir: 'docs'
site_dir: '../../static/modep/docs'
site_name: MODEP Documentation
site_author: UAB VILNIAUS BLOKAS
google_analytics: ['UA-44135535-1', 'auto']
use_directory_urls: true
theme:
  name: 'material'
  favicon: 'favicon.ico'
  logo: 'images/logo.svg'
  palette:
    primary: 'white'
    accent: 'white'
  custom_dir: 'blokas-docs-theme'
site_url: https://blokas.io/modep/docs/
extra:
  discourse: 'https://community.blokas.io/'
  disqus: 'fake'
  social:
    - type: 'github'
      link: 'https://github.com/BlokasLabs'
    - type: 'twitter'
      link: 'https://twitter.com/blokaslabs'
    - type: 'facebook'
      link: 'https://www.facebook.com/blokaslabs/'
repo_name: 'modep-docs'
repo_url: 'https://github.com/BlokasLabs/modep-docs/'
markdown_extensions:
  - toc:
      permalink: '#'
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - footnotes:
      PLACE_MARKER: '///Footnotes Go Here///'

copyright: '&copy; 2020 VILNIAUS BLOKAS UAB'

nav:
- Introduction: index.md
- Setup: Setup.md
- Running MODEP: Running-MODEP.md
- MODEP & Pisound: MODEP-and-Pisound.md
- Plugins: Plugins.md
- Guides & FAQs: FAQ.md
- Troubleshooting: Troubleshooting.md
- Contribution Guide: Contribution-Guide.md
- Changelog: Changelog.md
